#include "EERTOS_f3.h"

#define LED1L() GPIOE->BSRR = GPIO_BSRR_BR_8
#define LED2L() GPIOE->BSRR = GPIO_BSRR_BR_9
#define LED3L() GPIOE->BSRR = GPIO_BSRR_BR_10
#define LED4L() GPIOE->BSRR = GPIO_BSRR_BR_11
#define LED5L() GPIOE->BSRR = GPIO_BSRR_BR_12
#define LED6L() GPIOE->BSRR = GPIO_BSRR_BR_13
#define LED7L() GPIOE->BSRR = GPIO_BSRR_BR_14
#define LED8L() GPIOE->BSRR = GPIO_BSRR_BR_15

#define LED1H() GPIOE->BSRR = GPIO_BSRR_BS_8
#define LED2H() GPIOE->BSRR = GPIO_BSRR_BS_9
#define LED3H() GPIOE->BSRR = GPIO_BSRR_BS_10
#define LED4H() GPIOE->BSRR = GPIO_BSRR_BS_11
#define LED5H() GPIOE->BSRR = GPIO_BSRR_BS_12
#define LED6H() GPIOE->BSRR = GPIO_BSRR_BS_13
#define LED7H() GPIOE->BSRR = GPIO_BSRR_BS_14
#define LED8H() GPIOE->BSRR = GPIO_BSRR_BS_15


void Init_pins(void);
void Leds(void);
